setwd("/storage/math/projects/gnomad-public/gnomADv3.1.2/chr1")

library(dplyr)
library(data.table)
#read in variant lines from chr1
beforefilter_chr1 <- fread("gnomad.genomes.v3.1.2.merge.hgdp_tgp_summarydata.infoexpanded.chr1.vcf.gz")
#remove "-" from each column name
names(beforefilter_chr1) <- gsub("-", "", names(beforefilter_chr1))
#remove "_" from each column name
names(beforefilter_chr1) <- gsub("_", "", names(beforefilter_chr1))
#Change missing value denoted as "?" to "NA"
beforefilter_chr1 <- beforefilter_chr1 %>% dplyr::na_if("?")
#filter each AF: remove AF less than .01, greater than
chr1_AF_filtered <- beforefilter_chr1[(beforefilter_chr1$AFacb>0.01 & beforefilter_chr1$AFacb<0.99 & !is.na(beforefilter_chr1$AFacb)) 
                                        | (beforefilter_chr1$AFadygei>0.01 & beforefilter_chr1$AFadygei<0.99 & !is.na(beforefilter_chr1$AFadygei)) 
                                        | ( beforefilter_chr1$AFasw>0.01 & beforefilter_chr1$AFasw<0.99 & !is.na(beforefilter_chr1$AFasw))
                                        | (beforefilter_chr1$AFbalochi>0.01 & beforefilter_chr1$AFbalochi<0.99 & !is.na(beforefilter_chr1$AFbalochi))
                                        | (beforefilter_chr1$AFbantukenya>0.01 & beforefilter_chr1$AFbantukenya<0.99 & !is.na(beforefilter_chr1$AFbantukenya))
                                        | (beforefilter_chr1$AFbantusafrica>0.01 & beforefilter_chr1$AFbantusafrica<0.99 & !is.na(beforefilter_chr1$AFbantusafrica))
                                        | (beforefilter_chr1$AFbasque>0.01 & beforefilter_chr1$AFbasque<0.99 & !is.na(beforefilter_chr1$AFbasque))
                                        | (beforefilter_chr1$AFbeb>0.01 & beforefilter_chr1$AFbeb<0.99 & !is.na(beforefilter_chr1$AFbeb))
                                        | (beforefilter_chr1$AFbedouin>0.01 & beforefilter_chr1$AFbedouin<0.99 & !is.na(beforefilter_chr1$AFbedouin))
                                        | (beforefilter_chr1$AFbiakapygmy>0.01 & beforefilter_chr1$AFbiakapygmy<0.99 & !is.na(beforefilter_chr1$AFbiakapygmy))
                                        | (beforefilter_chr1$AFbrahui>0.01 & beforefilter_chr1$AFbrahui<0.99 & !is.na(beforefilter_chr1$AFbrahui))
                                        | (beforefilter_chr1$AFburusho>0.01 & beforefilter_chr1$AFburusho<0.99 & !is.na(beforefilter_chr1$AFburusho))
                                        | (beforefilter_chr1$AFcambodian>0.01 & beforefilter_chr1$AFcambodian<0.99 & !is.na(beforefilter_chr1$AFcambodian))
                                        | (beforefilter_chr1$AFcdx>0.01 & beforefilter_chr1$AFcdx<0.99 & !is.na(beforefilter_chr1$AFcdx))
                                        | (beforefilter_chr1$AFceu>0.01 & beforefilter_chr1$AFceu<0.99 & !is.na(beforefilter_chr1$AFceu))
                                        | (beforefilter_chr1$AFchb>0.01 & beforefilter_chr1$AFchb<0.99 & !is.na(beforefilter_chr1$AFchb))
                                        | (beforefilter_chr1$AFchs>0.01 & beforefilter_chr1$AFchs<0.99 & !is.na(beforefilter_chr1$AFchs))
                                        | (beforefilter_chr1$AFclm>0.01 & beforefilter_chr1$AFclm<0.99 & !is.na(beforefilter_chr1$AFclm))
                                        | (beforefilter_chr1$AFcolombian>0.01 & beforefilter_chr1$AFcolombian<0.99 & !is.na(beforefilter_chr1$AFcolombian))
                                        | (beforefilter_chr1$AFdai>0.01 & beforefilter_chr1$AFdai<0.99 & !is.na(beforefilter_chr1$AFdai))
                                        | (beforefilter_chr1$AFdaur>0.01 & beforefilter_chr1$AFdaur<0.99 & !is.na(beforefilter_chr1$AFdaur))
                                        | (beforefilter_chr1$AFdruze>0.01 & beforefilter_chr1$AFdruze<0.99 & !is.na(beforefilter_chr1$AFdruze))
                                        | (beforefilter_chr1$AFesn>0.01 & beforefilter_chr1$AFesn<0.99 & !is.na(beforefilter_chr1$AFesn))
                                        | (beforefilter_chr1$AFfin>0.01 & beforefilter_chr1$AFfin<0.99 & !is.na(beforefilter_chr1$AFfin))
                                        | (beforefilter_chr1$AFfrench>0.01 & beforefilter_chr1$AFfrench<0.99 & !is.na(beforefilter_chr1$AFfrench))
                                        | (beforefilter_chr1$AFgbr>0.01 & beforefilter_chr1$AFgbr<0.99 & !is.na(beforefilter_chr1$AFgbr))
                                        | (beforefilter_chr1$AFgih>0.01 & beforefilter_chr1$AFgih<0.99 & !is.na(beforefilter_chr1$AFgih))
                                        | (beforefilter_chr1$AFgwd>0.01 & beforefilter_chr1$AFgwd<0.99 & !is.na(beforefilter_chr1$AFgwd))
                                        | (beforefilter_chr1$AFhan>0.01 & beforefilter_chr1$AFhan<0.99 & !is.na(beforefilter_chr1$AFhan))
                                        | (beforefilter_chr1$AFhazara>0.01 & beforefilter_chr1$AFhazara<0.99 & !is.na(beforefilter_chr1$AFhazara))
                                        | (beforefilter_chr1$AFhezhen>0.01 & beforefilter_chr1$AFhezhen<0.99 & !is.na(beforefilter_chr1$AFhezhen))
                                        | (beforefilter_chr1$AFibs>0.01 & beforefilter_chr1$AFibs<0.99 & !is.na(beforefilter_chr1$AFibs))
                                        | (beforefilter_chr1$AFitalian>0.01 & beforefilter_chr1$AFitalian<0.99 & !is.na(beforefilter_chr1$AFitalian))
                                        | (beforefilter_chr1$AFitu>0.01 & beforefilter_chr1$AFitu<0.99 & !is.na(beforefilter_chr1$AFitu))
                                        | (beforefilter_chr1$AFjapanese>0.01 & beforefilter_chr1$AFjapanese<0.99 & !is.na(beforefilter_chr1$AFjapanese))
                                        | (beforefilter_chr1$AFjpt>0.01 & beforefilter_chr1$AFjpt<0.99 & !is.na(beforefilter_chr1$AFjpt))
                                        | (beforefilter_chr1$AFkalash>0.01 & beforefilter_chr1$AFkalash<0.99 & !is.na(beforefilter_chr1$AFkalash))
                                        | (beforefilter_chr1$AFkaritiana>0.01 & beforefilter_chr1$AFkaritiana<0.99 & !is.na(beforefilter_chr1$AFkaritiana))
                                        | (beforefilter_chr1$AFkhv>0.01 & beforefilter_chr1$AFkhv<0.99 & !is.na(beforefilter_chr1$AFkhv))
                                        | (beforefilter_chr1$AFlahu>0.01 & beforefilter_chr1$AFlahu<0.99 & !is.na(beforefilter_chr1$AFlahu))
                                        | (beforefilter_chr1$AFlwk>0.01 & beforefilter_chr1$AFlwk<0.99 & !is.na(beforefilter_chr1$AFlwk))
                                        | (beforefilter_chr1$AFmakrani>0.01 & beforefilter_chr1$AFmakrani<0.99 & !is.na(beforefilter_chr1$AFmakrani))
                                        | (beforefilter_chr1$AFmandenka>0.01 & beforefilter_chr1$AFmandenka<0.99 & !is.na(beforefilter_chr1$AFmandenka))
                                        | (beforefilter_chr1$AFmaya>0.01 & beforefilter_chr1$AFmaya<0.99 & !is.na(beforefilter_chr1$AFmaya))
                                        | (beforefilter_chr1$AFmelanesian>0.01 & beforefilter_chr1$AFmelanesian<0.99 & !is.na(beforefilter_chr1$AFmelanesian))
                                        | (beforefilter_chr1$AFmiaozu>0.01 & beforefilter_chr1$AFmiaozu<0.99 & !is.na(beforefilter_chr1$AFmiaozu))
                                        | (beforefilter_chr1$AFmongola>0.01 & beforefilter_chr1$AFmongola<0.99 & !is.na(beforefilter_chr1$AFmongola))
                                        | (beforefilter_chr1$AFmozabite>0.01 & beforefilter_chr1$AFmozabite<0.99 & !is.na(beforefilter_chr1$AFmozabite))
                                        | (beforefilter_chr1$AFmsl>0.01 & beforefilter_chr1$AFmsl<0.99 & !is.na(beforefilter_chr1$AFmsl))
                                        | (beforefilter_chr1$AFmxl>0.01 & beforefilter_chr1$AFmxl<0.99 & !is.na(beforefilter_chr1$AFmxl))
                                        | (beforefilter_chr1$AFmbutipygmy>0.01 & beforefilter_chr1$AFmbutipygmy<0.99 & !is.na(beforefilter_chr1$AFmbutipygmy))
                                        | (beforefilter_chr1$AFnaxi>0.01 & beforefilter_chr1$AFnaxi<0.99 & !is.na(beforefilter_chr1$AFnaxi))
                                        | (beforefilter_chr1$AForcadian>0.01 & beforefilter_chr1$AForcadian<0.99 & !is.na(beforefilter_chr1$AForcadian))
                                        | (beforefilter_chr1$AForoqen>0.01 & beforefilter_chr1$AForoqen<0.99 & !is.na(beforefilter_chr1$AForoqen))
                                        | (beforefilter_chr1$AFpalestinian>0.01 & beforefilter_chr1$AFpalestinian<0.99 & !is.na(beforefilter_chr1$AFpalestinian))
                                        | (beforefilter_chr1$AFpapuan>0.01 & beforefilter_chr1$AFpapuan<0.99 & !is.na(beforefilter_chr1$AFpapuan))
                                        | (beforefilter_chr1$AFpathan>0.01 & beforefilter_chr1$AFpathan<0.99 & !is.na(beforefilter_chr1$AFpathan))
                                        | (beforefilter_chr1$AFpel>0.01 & beforefilter_chr1$AFpel<0.99 & !is.na(beforefilter_chr1$AFpel))
                                        | (beforefilter_chr1$AFpima>0.01 & beforefilter_chr1$AFpima<0.99 & !is.na(beforefilter_chr1$AFpima))
                                        | (beforefilter_chr1$AFpjl>0.01 & beforefilter_chr1$AFpjl<0.99 & !is.na(beforefilter_chr1$AFpjl))
                                        | (beforefilter_chr1$AFpur>0.01 & beforefilter_chr1$AFpur<0.99 & !is.na(beforefilter_chr1$AFpur))
                                        | (beforefilter_chr1$AFrussian>0.01 & beforefilter_chr1$AFrussian<0.99 & !is.na(beforefilter_chr1$AFrussian))
                                        | (beforefilter_chr1$AFsan>0.01 & beforefilter_chr1$AFsan<0.99 & !is.na(beforefilter_chr1$AFsan))
                                        | (beforefilter_chr1$AFsardinian>0.01 & beforefilter_chr1$AFsardinian<0.99 & !is.na(beforefilter_chr1$AFsardinian))
                                        | (beforefilter_chr1$AFshe>0.01 & beforefilter_chr1$AFshe<0.99 & !is.na(beforefilter_chr1$AFshe))
                                        | (beforefilter_chr1$AFsindhi>0.01 & beforefilter_chr1$AFsindhi<0.99 & !is.na(beforefilter_chr1$AFsindhi))
                                        | (beforefilter_chr1$AFstu>0.01 & beforefilter_chr1$AFstu<0.99 & !is.na(beforefilter_chr1$AFstu))
                                        | (beforefilter_chr1$AFsurui>0.01 & beforefilter_chr1$AFsurui<0.99 & !is.na(beforefilter_chr1$AFsurui))
                                        | (beforefilter_chr1$AFtsi>0.01 & beforefilter_chr1$AFtsi<0.99 & !is.na(beforefilter_chr1$AFtsi))
                                        | (beforefilter_chr1$AFtu>0.01 & beforefilter_chr1$AFtu<0.99 & !is.na(beforefilter_chr1$AFtu))
                                        | (beforefilter_chr1$AFtujia>0.01 & beforefilter_chr1$AFtujia<0.99 & !is.na(beforefilter_chr1$AFtujia))
                                        | (beforefilter_chr1$AFtuscan>0.01 & beforefilter_chr1$AFtuscan<0.99 & !is.na(beforefilter_chr1$AFtuscan))
                                        | (beforefilter_chr1$AFuygur>0.01 & beforefilter_chr1$AFuygur<0.99 & !is.na(beforefilter_chr1$AFuygur))
                                        | (beforefilter_chr1$AFxibo>0.01 & beforefilter_chr1$AFxibo<0.99 & !is.na(beforefilter_chr1$AFxibo))
                                        | (beforefilter_chr1$AFyakut>0.01 & beforefilter_chr1$AFyakut<0.99 & !is.na(beforefilter_chr1$AFyakut))
                                        | (beforefilter_chr1$AFyizu>0.01 & beforefilter_chr1$AFyizu<0.99 & !is.na(beforefilter_chr1$AFyizu))
                                        | (beforefilter_chr1$AFyoruba>0.01 & beforefilter_chr1$AFyoruba<0.99 & !is.na(beforefilter_chr1$AFyoruba))
                                        | (beforefilter_chr1$AFyri>0.01 & beforefilter_chr1$AFyri<0.99 & !is.na(beforefilter_chr1$AFyri)) 
                                        | (beforefilter_chr1$AFnonneuronfe>0.01 & beforefilter_chr1$AFnonneuronfe<0.99 & !is.na(beforefilter_chr1$AFnonneuronfe))
                                        | (beforefilter_chr1$AFnonv2>0.01 & beforefilter_chr1$AFnonv2<0.99 & !is.na(beforefilter_chr1$AFnonv2))
                                        | (beforefilter_chr1$AFnonv2mid>0.01 & beforefilter_chr1$AFnonv2mid<0.99 & !is.na(beforefilter_chr1$AFnonv2mid))
                                        | (beforefilter_chr1$AFnontopmedsas>0.01 & beforefilter_chr1$AFnontopmedsas<0.99 & !is.na(beforefilter_chr1$AFnontopmedsas))
                                        | (beforefilter_chr1$AFoth>0.01 & beforefilter_chr1$AFoth<0.99 & !is.na(beforefilter_chr1$AFoth))
                                        | (beforefilter_chr1$AFnonneurofin>0.01 & beforefilter_chr1$AFnonneurofin<0.99 & !is.na(beforefilter_chr1$AFnonneurofin)) 
                                        | (beforefilter_chr1$AFnonv2asj>0.01 & beforefilter_chr1$AFnonv2asj<0.99 & !is.na(beforefilter_chr1$AFnonv2asj))
                                        | (beforefilter_chr1$AFcontrolsandbiobanksami>0.01 & beforefilter_chr1$AFcontrolsandbiobanksami<0.99 & !is.na(beforefilter_chr1$AFcontrolsandbiobanksami))
                                        | (beforefilter_chr1$AFnontopmedeas>0.01 & beforefilter_chr1$AFnontopmedeas<0.99 & !is.na(beforefilter_chr1$AFnontopmedeas))
                                        | (beforefilter_chr1$AFnonv2amr>0.01 & beforefilter_chr1$AFnonv2amr<0.99 & !is.na(beforefilter_chr1$AFnonv2amr))
                                        | (beforefilter_chr1$AFnonneurosas>0.01 & beforefilter_chr1$AFnonneurosas<0.99 & !is.na(beforefilter_chr1$AFnonneurosas))
                                        | (beforefilter_chr1$AFnonv2oth>0.01 & beforefilter_chr1$AFnonv2oth<0.99 & !is.na(beforefilter_chr1$AFnonv2oth))
                                        | (beforefilter_chr1$AFami>0.01 & beforefilter_chr1$AFami<0.99 & !is.na(beforefilter_chr1$AFami))
                                        | (beforefilter_chr1$AFnonv2sas>0.01 & beforefilter_chr1$AFnonv2sas<0.99 & !is.na(beforefilter_chr1$AFnonv2sas))
                                        | (beforefilter_chr1$AFsas>0.01 & beforefilter_chr1$AFsas<0.99 & !is.na(beforefilter_chr1$AFsas))
                                        | (beforefilter_chr1$AFnoncancereas>0.01 & beforefilter_chr1$AFnoncancereas<0.99 & !is.na(beforefilter_chr1$AFnoncancereas))
                                        | (beforefilter_chr1$AFnonv2ami>0.01 & beforefilter_chr1$AFnonv2ami<0.99 & !is.na(beforefilter_chr1$AFnonv2ami))
                                        | (beforefilter_chr1$AFnonneuro>0.01 & beforefilter_chr1$AFnonneuro<0.99 & !is.na(beforefilter_chr1$AFnonneuro))
                                        | (beforefilter_chr1$AFcontrolsandbiobankseas>0.01 & beforefilter_chr1$AFcontrolsandbiobankseas<0.99 & !is.na(beforefilter_chr1$AFcontrolsandbiobankseas))
                                        | (beforefilter_chr1$AFfin>0.01 & beforefilter_chr1$AFfin<0.99 & !is.na(beforefilter_chr1$AFfin))
                                        | (beforefilter_chr1$AFcontrolsandbiobanksafr>0.01 & beforefilter_chr1$AFcontrolsandbiobanksafr<0.99 & !is.na(beforefilter_chr1$AFcontrolsandbiobanksafr))
                                        | (beforefilter_chr1$AFnontopmedmid>0.01 & beforefilter_chr1$AFnontopmedmid<0.99 & !is.na(beforefilter_chr1$AFnontopmedmid))
                                        | (beforefilter_chr1$AFnontopmed>0.01 & beforefilter_chr1$AFnontopmed<0.99 & !is.na(beforefilter_chr1$AFnontopmed))
                                        | (beforefilter_chr1$AFnontopmedamr>0.01 & beforefilter_chr1$AFnontopmedamr<0.99 & !is.na(beforefilter_chr1$AFnontopmedamr))
                                        | (beforefilter_chr1$AFcontrolsandbiobanksamr>0.01 & beforefilter_chr1$AFcontrolsandbiobanksamr<0.99 & !is.na(beforefilter_chr1$AFcontrolsandbiobanksamr))
                                        | (beforefilter_chr1$AFnonneuromid>0.01 & beforefilter_chr1$AFnonneuromid<0.99 & !is.na(beforefilter_chr1$AFnonneuromid))
                                        | (beforefilter_chr1$AFnonv2afr>0.01 & beforefilter_chr1$AFnonv2afr<0.99 & !is.na(beforefilter_chr1$AFnonv2afr))
                                        | (beforefilter_chr1$AFnoncancerafr>0.01 & beforefilter_chr1$AFnoncancerafr<0.99 & !is.na(beforefilter_chr1$AFnoncancerafr))
                                        | (beforefilter_chr1$AFcontrolsandbiobanksfin>0.01 & beforefilter_chr1$AFcontrolsandbiobanksfin<0.99 & !is.na(beforefilter_chr1$AFcontrolsandbiobanksfin))
                                        | (beforefilter_chr1$AFnoncancerami>0.01 & beforefilter_chr1$AFnoncancerami<0.99 & !is.na(beforefilter_chr1$AFnoncancerami))
                                        | (beforefilter_chr1$AFeas>0.01 & beforefilter_chr1$AFeas<0.99 & !is.na(beforefilter_chr1$AFeas))
                                        | (beforefilter_chr1$AFnontopmednfe>0.01 & beforefilter_chr1$AFnontopmednfe<0.99 & !is.na(beforefilter_chr1$AFnontopmednfe))
                                        | (beforefilter_chr1$AFamr>0.01 & beforefilter_chr1$AFamr<0.99 & !is.na(beforefilter_chr1$AFamr))
                                        | (beforefilter_chr1$AFnonneuroami>0.01 & beforefilter_chr1$AFnonneuroami<0.99 & !is.na(beforefilter_chr1$AFnonneuroami))
                                        | (beforefilter_chr1$AFnoncancermid>0.01 & beforefilter_chr1$AFnoncancermid<0.99 & !is.na(beforefilter_chr1$AFnoncancermid))
                                        | (beforefilter_chr1$AFafr>0.01 & beforefilter_chr1$AFafr<0.99 & !is.na(beforefilter_chr1$AFafr))
                                        | (beforefilter_chr1$AFnoncancersas>0.01 & beforefilter_chr1$AFnoncancersas<0.99 & !is.na(beforefilter_chr1$AFnoncancersas))
                                        | (beforefilter_chr1$AFnontopmedfin>0.01 & beforefilter_chr1$AFnontopmedfin<0.99 & !is.na(beforefilter_chr1$AFnontopmedfin))
                                        | (beforefilter_chr1$AFcontrolsandbiobanksmid>0.01 & beforefilter_chr1$AFcontrolsandbiobanksmid<0.99 & !is.na(beforefilter_chr1$AFcontrolsandbiobanksmid))
                                        | (beforefilter_chr1$AFcontrolsandbiobankssas>0.01 & beforefilter_chr1$AFcontrolsandbiobankssas<0.99 & !is.na(beforefilter_chr1$AFcontrolsandbiobankssas))
                                        | (beforefilter_chr1$AFnonv2eas>0.01 & beforefilter_chr1$AFnonv2eas<0.99 & !is.na(beforefilter_chr1$AFnonv2eas))
                                        | (beforefilter_chr1$AFmid>0.01 & beforefilter_chr1$AFmid<0.99 & !is.na(beforefilter_chr1$AFmid))
                                        | (beforefilter_chr1$AFnoncancernfe>0.01 & beforefilter_chr1$AFnoncancernfe<0.99 & !is.na(beforefilter_chr1$AFnoncancernfe))
                                        | (beforefilter_chr1$AFnontopmedasj>0.01 & beforefilter_chr1$AFnontopmedasj<0.99 & !is.na(beforefilter_chr1$AFnontopmedasj))
                                        | (beforefilter_chr1$AFasj>0.01 & beforefilter_chr1$AFasj<0.99 & !is.na(beforefilter_chr1$AFasj))
                                        | (beforefilter_chr1$AFnontopmedami>0.01 & beforefilter_chr1$AFnontopmedami<0.99 & !is.na(beforefilter_chr1$AFnontopmedami))
                                        | (beforefilter_chr1$AFnoncancer>0.01 & beforefilter_chr1$AFnoncancer<0.99 & !is.na(beforefilter_chr1$AFnoncancer))
                                        | (beforefilter_chr1$AFnonv2fin>0.01 & beforefilter_chr1$AFnonv2fin<0.99 & !is.na(beforefilter_chr1$AFnonv2fin))
                                        | (beforefilter_chr1$AFnonneurooth>0.01 & beforefilter_chr1$AFnonneurooth<0.99 & !is.na(beforefilter_chr1$AFnonneurooth))
                                        | (beforefilter_chr1$AFnonneuroasj>0.01 & beforefilter_chr1$AFnonneuroasj<0.99 & !is.na(beforefilter_chr1$AFnonneuroasj))
                                        | (beforefilter_chr1$AFnontopmedafr>0.01 & beforefilter_chr1$AFnontopmedafr<0.99 & !is.na(beforefilter_chr1$AFnontopmedafr))
                                        | (beforefilter_chr1$AFnonneuroeas>0.01 & beforefilter_chr1$AFnonneuroeas<0.99 & !is.na(beforefilter_chr1$AFnonneuroeas))
                                        | (beforefilter_chr1$AFnoncanceramr>0.01 & beforefilter_chr1$AFnoncanceramr<0.99 & !is.na(beforefilter_chr1$AFnoncanceramr))
                                        | (beforefilter_chr1$AFcontrolsandbiobanks>0.01 & beforefilter_chr1$AFcontrolsandbiobanks<0.99 & !is.na(beforefilter_chr1$AFcontrolsandbiobanks))
                                        | (beforefilter_chr1$AFcontrolsandbiobanksoth>0.01 & beforefilter_chr1$AFcontrolsandbiobanksoth<0.99 & !is.na(beforefilter_chr1$AFcontrolsandbiobanksoth))
                                        | (beforefilter_chr1$AFnoncanceroth>0.01 & beforefilter_chr1$AFnoncanceroth<0.99 & !is.na(beforefilter_chr1$AFnoncanceroth))
                                        | (beforefilter_chr1$AFnontopmedoth>0.01 & beforefilter_chr1$AFnontopmedoth<0.99 & !is.na(beforefilter_chr1$AFnontopmedoth))
                                        | (beforefilter_chr1$AFnonv2nfe>0.01 & beforefilter_chr1$AFnonv2nfe<0.99 & !is.na(beforefilter_chr1$AFnonv2nfe))
                                        | (beforefilter_chr1$AFcontrolsandbiobanksnfe>0.01 & beforefilter_chr1$AFcontrolsandbiobanksnfe<0.99 & !is.na(beforefilter_chr1$AFcontrolsandbiobanksnfe))
                                        | (beforefilter_chr1$AFnoncancerasj>0.01 & beforefilter_chr1$AFnoncancerasj<0.99 & !is.na(beforefilter_chr1$AFnoncancerasj))
                                        | (beforefilter_chr1$AFnonneuroamr>0.01 & beforefilter_chr1$AFnonneuroamr<0.99 & !is.na(beforefilter_chr1$AFnonneuroamr))
                                        | (beforefilter_chr1$AFnonneuroafr>0.01 & beforefilter_chr1$AFnonneuroafr<0.99 & !is.na(beforefilter_chr1$AFnonneuroafr))
                                        | (beforefilter_chr1$AFnoncancerfin>0.01 & beforefilter_chr1$AFnoncancerfin<0.99 & !is.na(beforefilter_chr1$AFnoncancerfin))
                                        | (beforefilter_chr1$AFcontrolsandbiobanksasj>0.01 & beforefilter_chr1$AFcontrolsandbiobanksasj<0.99 & !is.na(beforefilter_chr1$AFcontrolsandbiobanksasj))
                                        | (beforefilter_chr1$AFnfe>0.01 & beforefilter_chr1$AFnfe<0.99 & !is.na(beforefilter_chr1$AFnfe)),] 


#remove all NA's and compare difference
chr1AFfilteredallNAremoved <- na.omit(chr1_AF_filtered)

#Create table 
write.table(chr1AFfilteredallNAremoved, file="chr1AFfilteredallNAremoved.txt", sep="\t", quote = FALSE, row.names=F,col.names=T)




